version: '3'
services:
  app:
    container_name: go_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - go-dock-postgres  # Uncomment this when using postgres.
      # - go-dock-mysql     # Uncomment this when using mysql.
    networks:
      - go-docker


  go-dock-postgres:
    image: postgres:latest
    container_name: go_db_pg
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - go-docker
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pagadmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - go-dock-postgres
    ports:
      - "5050:80"
    networks:
      - go-docker
    restart: unless-stopped


  # go-dock-mysql:
  #   image: mysql:5.7
  #   container_name: go_db_mysql
  #   ports: 
  #     - 3306:3306
  #   environment: 
  #     - MYSQL_ROOT_HOST=${DB_HOST} 
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - database_mysql:/var/lib/mysql
  #   networks:
  #     - go-docker
  
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin_container
  #   depends_on:
  #     - go-dock-mysql
  #   environment:
  #     - PMA_HOST=mysql # Note the "mysql". Must be the name of the what you used as the mysql service.
  #     - PMA_USER=${DB_USER}
  #     - PMA_PORT=${DB_PORT}
  #     - PMA_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - 9090:80
  #   restart: always
  #   networks:
  #     - go-docker


volumes:
  api:
  database_postgres:  # Uncomment this when using postgres.
  # database_mysql:     # Uncomment this when using mysql.

# Networks to be created to facilitate communication between containers
networks:
  go-docker:
    driver: bridge