version: '3'

services:
  app_test:
    container_name: go_app_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - api_test:/app/src/app/
    depends_on:
      - postgres_test   # Uncomment this when using postgres.
      # - mysql_test      # Uncomment this when using mysql.
    networks:
      - go-docker-test

  postgres_test:
    image: postgres:latest
    container_name: go_db_pg_test
    environment:
      - POSTGRES_USER="${TEST_DB_USER}"
      - POSTGRES_PASSWORD="${TEST_DB_PASSWORD}"
      - POSTGRES_DB="${TEST_DB_NAME}"
      - POSTGRES_HOST="${TEST_DB_HOST}"
    ports:
      - '5555:5432'
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - go-docker-test
  
  # mysql_test:
  #   image: mysql:5.7
  #   container_name: go_db_mysql_test    
  #   ports: 
  #     - 3333:3306
  #   environment: 
  #     - MYSQL_DATABASE=${TEST_DB_NAME}
  #     - MYSQL_USER=${TEST_DB_USER}
  #     - MYSQL_PASSWORD=${TEST_DB_PASSWORD}
  #     - MYSQL_ROOT_PASSWORD=${TEST_DB_PASSWORD}
  #     - DATABASE_HOST=${TEST_DB_HOST} 
  #   volumes:
  #     - database_mysql_test:/var/lib/mysql
  #   networks:
  #     - go-docker-test

volumes:
  api_test:
  database_postgres_test:   # Uncomment this when using postgres.
  # database_mysql_test:      # Uncomment this when using mysql.

networks:
  go-docker-test:
    driver: bridge